esphome:
  name: sdi12-weather
  platform: ESP32
  board: nodemcu-32s

external_components:
  - source:
      type: local
      path: custom_components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SDI-12 Fallback Hotspot"
    password: !secret fallback_password

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

sdi12:
  rx_pin: 25
  tx_pin: 26
  enable_pin: 27
  scan: False
  id: bus_a

sensor:
  - platform: ds2
    address: 5
    wind_speed:
      name: "Windspeed"
      id: ds2_windspeed
  - platform: cs215
    address: 0
    temperature:
      name: "Temperature"
      id: outside_temperature
    humidity:
      name: "Humidity"
      id: outside_humidity
