M48
; DRILL file {KiCad 7.0.8} date Mo 13 Nov 2023 22:43:03 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-13T22:43:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0886
%
G90
G05
T1
X1.9063Y-1.9764
X1.9063Y-4.0236
X2.8906Y-1.9764
X2.8906Y-4.0236
T0
M30
